apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: loadwrmv9766-tenant-component
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: loadwrmv9766-tenant-component
    app.kubernetes.io/part-of: loadwrmv9766-tenant-app
  name: loadwrmv9766-tenant-component
  namespace: loadwrmv9766-tenant
spec:
  path: /
  port:
    targetPort: 8081
  to:
    kind: Service
    name: loadwrmv9766-tenant-component
    weight: null
status: {}
